spring.application.name=online_examination_system
spring.datasource.url=jdbc:postgresql://localhost:5432/OnlineExaminationSystem
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update